FROM python:3.11-slim

WORKDIR /app

# Instala dependências do sistema necessárias para algumas bibliotecas
RUN apt-get update && apt-get install -y build-essential curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia código
COPY src/ src/

# Inicia o servidor
CMD ["uvicorn", "src.unofficial_main:app", "--host", "0.0.0.0", "--port", "8000"]
